# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies via uv
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      flask-ecosystem:
        patterns:
          - "flask*"
          - "wtforms*"
          - "sqlalchemy*"
      testing-tools:
        patterns:
          - "pytest*"
          - "playwright*"
      linting-tools:
        patterns:
          - "ruff*"
          - "pyright*"
          - "pre-commit*"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/app/static"
    schedule:
      interval: "daily"
    groups:
      ui-frameworks:
        patterns:
          - "flowbite*"
          - "@tailwindcss/*"
          - "tailwindcss"

  # GitHub Actions & pre-commit hooks
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
