services:
    wizarr-plus:
        build:
            context: .
            dockerfile: Dockerfile.plus
        ports:
            - 5690:5690
        volumes:
            - ./test-data:/data/database
        environment:
            - TZ=Europe/London
            - WIZARR_PLUS_ENABLED=true
            - WIZARR_PLUS_COMPILED=true