{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.wizarr_container_name, values.wizarr.image_selector) %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}

{% do c1.set_user(values.run_as.user, values.run_as.group) %}
{% do c1.healthcheck.set_test("curl", {"port": values.network.web_port.port_number, "path": "/", "scheme": "http"}) %}
{% do c1.environment.add_env("PUID", values.run_as.user) %}
{% do c1.environment.add_env("PGID", values.run_as.group) %}
{% do c1.environment.add_env("TZ", values.TZ) %}
{% do c1.environment.add_env("DISABLE_BUILTIN_AUTH", values.wizarr.disable_builtin_auth | string | lower) %}
{% do c1.environment.add_user_envs(values.wizarr.additional_envs) %}

{% do c1.add_port(values.network.web_port) %}

{% do c1.add_storage("/data/database", values.storage.database) %}
{% do perm_container.add_or_skip_action("database", values.storage.database, perms_config) %}

{% do c1.add_storage("/data/wizard_steps", values.storage.wizard) %}
{% do perm_container.add_or_skip_action("wizard", values.storage.wizard, perms_config) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.web_port) %}
{% do tpl.notes.set_body("Default credentials will be generated on first run.") %}

{{ tpl.render() | tojson }}
