resources:
  limits:
    cpus: 2.0
    memory: 2048

wizarr:
  image_selector: image
  disable_builtin_auth: false
  additional_envs: []
network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 5690

run_as:
  user: 568
  group: 568

ix_volumes:
  database: /opt/tests/mnt/wizarr-database
  wizard: /opt/tests/mnt/wizarr-wizard

storage:
  database:
    type: ix_volume
    ix_volume_config:
      dataset_name: database
      create_host_path: true
  wizard:
    mount_path: /data/wizard_steps
    type: ix_volume
    ix_volume_config:
      dataset_name: wizard
      create_host_path: true
  additional_storage: []
