annotations:
  min_scale_version: 24.10.2.2
app_version: 2025.6.4
capabilities: []
categories:
- media
- management
changelog_url: https://github.com/wizarrrr/wizarr/releases
date_added: '2025-06-21'
description: Wizarr is an invitation management system for Plex, Jellyfin, and Emby servers.
home: https://wizarr.dev/
host_mounts: []
icon: https://media.sys.truenas.net/apps/wizarr/icons/icon.png
keywords:
- media
- plex
- jellyfin
- emby
- invitations
lib_version: 2.1.35
lib_version_hash: 1bd4e0058fbd4d7c207df2cae606580065e8e6dba3e232f41bc1b006848b05d2
maintainers:
- email: dev@wizarr.dev
  name: wizarr
  url: https://github.com/wizarrrr/wizarr
name: wizarr
run_as_context:
- description: Wizarr runs as any non-root user.
  gid: 568
  group_name: wizarr
  uid: 568
  user_name: wizarr
screenshots:
- https://media.sys.truenas.net/apps/wizarr/screenshots/screenshot1.png
sources:
- https://github.com/wizarrrr/wizarr
title: Wizarr
train: community
version: 1.0.0
