name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --platform=linux/arm64 -t ghcr.io/wizarrrr/wizarr:arm64 . && docker build --platform=linux/amd64 -t ghcr.io/wizarrrr/wizarr:latest . && docker build --platform=linux/amd64 -t wizarr/wizarr:latest . && docker build --platform=linux/arm64 -t wizarr/wizarr:arm64 . && docker push ghcr.io/wizarrrr/wizarr:latest && docker push ghcr.io/wizarrrr/wizarr:arm64 && docker push wizarr/wizarr:latest && docker push wizarr/wizarr:arm64

