name: Build and push Docker image

on:
  push:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wizarrrr/wizarr

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images : ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags : dev # use a fixed tag 

      - name: Build and push Docker image
        uses : docker/build-push-action@v2 
        with :
          context : .
          file : ./Dockerfile
          platforms : linux/amd64,linux/arm64,linux/arm/v7 # specify architectures here 
          push : true # set this to false if you don't want to push 
          tags : ${{ steps.meta.outputs.tags }} # use metadata action output 
          labels : ${{ steps.meta.outputs.labels }} # use metadata action output 
