name: Force Ruff Fix

on:
  workflow_dispatch:

jobs:
  force-ruff-fix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: pyproject.toml

    - name: Install dependencies
      run: uv sync

    - name: Show file info before
      run: |
        echo "=== File info before ==="
        ls -la app/extensions.py
        wc -l app/extensions.py
        head -15 app/extensions.py

    - name: Force Ruff fix
      run: |
        echo "=== Running Ruff fix ==="
        uv run ruff check --fix app/extensions.py || true
        uv run ruff format app/extensions.py || true

    - name: Show file info after
      run: |
        echo "=== File info after ==="
        ls -la app/extensions.py
        wc -l app/extensions.py
        head -15 app/extensions.py

    - name: Test Ruff check
      run: |
        echo "=== Testing Ruff check ==="
        uv run ruff check --output-format=github app/extensions.py
        uv run ruff check --output-format=github .

    - name: Commit changes if any
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app/extensions.py
          git commit -m "fix(ci): force correct ruff formatting for extensions.py"
          git push
        else
          echo "No changes to commit"
        fi