name: Run Tests

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor != 'weblate'
    steps:
    - uses: actions/checkout@v4

    -   name: Install uv
        uses: astral-sh/setup-uv@v5
        
    -   name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version-file: pyproject.toml
    
    - name: Run tests
      run: |
        uv run pytest