name: RC Pre-release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  create-prerelease:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true && 
      startsWith(github.event.pull_request.title, 'RC v') &&
      github.repository_owner == 'wizarrrr'
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Extract RC version
        id: version
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          RC_VERSION=$(echo "$PR_TITLE" | sed 's/RC v//')
          echo "rc_version=$RC_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$RC_VERSION" >> $GITHUB_OUTPUT
      
      - name: Create GitHub Pre-release
        id: create_prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          # Extract changelog from PR body (remove the footer)
          PR_BODY="${{ github.event.pull_request.body }}"
          CHANGELOG=$(echo "$PR_BODY" | sed '/^---$/,$d')
          
          # Create the pre-release
          gh release create "${{ steps.version.outputs.tag }}" \
            --title "${{ steps.version.outputs.tag }}" \
            --notes "$CHANGELOG" \
            --prerelease
          
          # Get the release URL for summary
          RELEASE_URL=$(gh release view "${{ steps.version.outputs.tag }}" --json url --jq .url)
          echo "html_url=$RELEASE_URL" >> $GITHUB_OUTPUT
      
      - name: Summary
        run: |
          echo "🧪 **RC Pre-release Created!**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.version.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Release URL**: ${{ steps.create_prerelease.outputs.html_url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This will trigger beta Docker builds and deployment!" >> $GITHUB_STEP_SUMMARY