name: Run Tailwind CSS

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: app/static
      run: npm install
    - name: Build CSS
      working-directory: app/static
      run: npx tailwindcss -o css/main.css --minify
    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "Github Actions"
        git add app/static/
        git commit -m "Minifed CSS"
        git push