name: Run Tailwind CSS

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: app/static
      run: npm install
    - name: Build CSS
      working-directory: app/static
      run: npx tailwindcss -o css/main.css --minify
