name: Run Tailwind CSS

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      working-directory: app/static
      run: npm ci
    - name: Build CSS
      working-directory: app/static
      run: npx tailwindcss -o css/main.css --minify
    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        if output="$(git status --porcelain)" && [ -z "$output" ]; then
            echo "Nothing to commit."
        else 
            git add app/static/
            git commit -m "Minifed CSS"
            git push
        fi
