name: Update translations

on:
  push:

jobs:
  update_translations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Update Translation Messages
      run: |
        pybabel extract -F babel.cfg -k _l -o messages.pot .
    - name: Update Existing Translations with new messages
      run: |
        pybabel update -i messages.pot -d app/translations
    - name : Compile Translations
      run: |
        pybabel compile -d app/translations 

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "Github Actions"
        git add app/translations/
        git add messages.pot
        git commit -m "GA Update translations"
        git push