name: docker-ci-version

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare parameters
        id: prep
        run: |
          VERSION=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          VERSION_TAG="${DOCKER_IMAGE}:${VERSION}"
          TAGS="${VERSION_TAG}, ${DOCKER_IMAGE}:latest"
          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
      - name: Log into registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images : ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses : docker/build-push-action@v2 
        with :
          platforms : linux/amd64,linux/arm64,linux/arm/v7 # specify architectures here 
          context : .
          file : ./Dockerfile
          tags : ${{ steps.prep.outputs.tags }} # use metadata action output 
          push : true # set this to false if you don't want to push 
          labels : ${{ steps.meta.outputs.labels }} # use metadata action output 
